### ISSUE TITLE
Does not play well with CheckboxSetField

### ISSUE THREAD

**Issue by PeterBroom** [silverstripe/silverstripe-multiform#34]
When using a CheckboxSetField the data is stored as 1{comma}3 for example rather than 1,3

Example:

if($GetData = DataList::create('GetData')){
   $fields->push( new CheckboxSetField('GetData', 'Name', $GetData->map('ID', 'Name')->toArray()));
}

**Comment by wilr** [comment]
Hi @PeterBroom The display will be down to wherever you are displaying it. I tested this locally and finish() correctly gets an array of data with a CheckboxField. The module doesn't handle any saving / formatting of data. That is up to your application code.

**Comment by wilr** [comment]
Also confirmed that the string would be returned from CheckboxSet and frameworks Form::getData() so fix might be framework level.
