### ISSUE TITLE
Browser Validation

### ISSUE THREAD

**Issue by tekurinui** [silverstripe/silverstripe-multiform#37]
Hey,

If the back button is pressed then the required="required" attribute on fields causes the browser "Please fill in this field" popup to fire, which is not what you want when going back.

To get around it I added this to my template:

    <script type='text/javascript'>
      $(document).ready(function () {
          $('input[name="action_prev"]').on('click', function(){
            $('input[required="required"]').removeAttr('required');
          });
       });
    </script>

Not an issue as such, but thought you might want to know.

**Comment by wilr** [comment]
Fixed with formnovalidate label.
