### ISSUE TITLE
Mutliform - Validation exemption not working properly

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-multiform#4]
From http://open.silverstripe.org/ticket/6064

A bug arise when we try to exempt the validation on certain steps using the mecanism provided by MultiForm?.

Since the multiform inherits from class Form, you have to realised that a default validator is created when you try to exempt validation. In the form object, the code :

// Form validation
$this->validator = ($validator) ? $validator : new RequiredFields();
$this->validator->setForm($this);
will force the create of a RequiredFields? Object. The requireFields object launch a validate method. At first all the field in the forms must be valid, then the Required fields are verified.

This is the exact opposite of what we want. No Validation.

Since this behavior is set in the parent contructor, it is quite difficult to remove it from Silverstripe core. Besides, many side effect can occur by just altering the two lines above.

My suggestion is to do the validation check after the

// Give the fields, actions, and validation for the current step back to the parent Form class
parent::__construct($controller, $name, $fields, $actions, $validator);
Once it is verify that you don't need the validation , you can just do the following :

$this->unsetValidator();
In the __construct of the multiform you will have line looking like this

// Check if the $_REQUEST action that user clicked is an exempt one
$actionNames = Object::get_static(get_class($this),'actions_exempt_from_validation');
if( $actionNames ) {
	foreach( $actionNames as $exemptAction) {
		if(!empty($_REQUEST[$exemptAction])) {
			$this->unsetValidator();
			break;
		} 
        }
}
To test this setup a ReCAPTCHA Field and try to go to the previous step.

I join a patch file of what I think should work. I'll test it shortly: http://open.silverstripe.org/attachment/ticket/6064/Exempt-fix.patch

**Comment by wilr** [comment]
Fixed.
