### ISSUE TITLE
master branch uses 4.0 compatible code, but depends on ~3.2

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-multiform#47]
See declaration of augmentSQL.

https://github.com/silverstripe/silverstripe-multiform/blob/0ac61db2775ea7595f982df3293165df63d42c28/code/extensions/MultiFormObjectDecorator.php#L27

https://travis-ci.org/silverstripe/silverstripe-multiform/jobs/91978187

**Comment by spekulatius** [comment]
Do you want to close this @tractorcow ?

**Comment by tractorcow** [comment]
Nice job. :D
