### ISSUE TITLE
Next Step doesn't work anymore on 3.2.x

### ISSUE THREAD

**Issue by spekulatius** [silverstripe/silverstripe-multiform#51]
After the upgrade from CMS/FW 3.1.16 to 3.2.1 the multistep form doesn't work anymore. After the click on "next" the same step will be displayed. Did anyone notice this problem as well? @tractorcow can you confirm this issue?

**Comment by tractorcow** [comment]
Sorry but I haven't tested this module with 3.2.x yet.

Does the next-step work with 3.2.0, just not with 3.2.1?

**Comment by spekulatius** [comment]
I have tried it with 3.2.0 and the same issue happens.

**Comment by spekulatius** [comment]
I spent a few minutes looking into this. After removing

    	private static $get_var = 'MyCustomSessionID';

everything worked fine with FW 3.2.0. The issue isn't related to the FW version directly. With FW 3.2.x comes Multiform 1.2.0 while the former releases of the multiform required 3.1.x 

I figured out that latest release 1.2.0 doesn't contain all commits from 1.0 and 1.1. For example https://github.com/silverstripe/silverstripe-multiform/commit/59cc14b347760a7ddcce30254a55cf027a076028 is missing - the commit implementing the option to define the $get_var ... Can we merge 1.0 and 1.1 into master @tractorcow and release 1.2.1?

**Comment by tractorcow** [comment]
1.0 was already merged into 1.1, but I've now merged up 1.1 into master. Do you want to test it out before I re-tag a new 1.2 release? https://github.com/silverstripe/silverstripe-multiform/commit/243caeb579b721aa8ac77bd7e74b6728e88c9b28

**Comment by spekulatius** [comment]
I found one more case where MultiFormSessionID was hard coded and fixed this here: https://github.com/silverstripe/silverstripe-multiform/pull/53

Could you also merge this one in: https://github.com/silverstripe/silverstripe-multiform/pull/52 ?

**Comment by cjsewell** [comment]
As there is no official release for this fix yet I have set composer for this plugin to version "dev-master" at this time. Any idea when I can change this to an actual version as even though I have set this to 'dev-master' the next step does not seem to progress past step 2 of my form

**Comment by spekulatius** [comment]
Should we close this @tractorcow ?

**Comment by kiwimediapro** [comment]
I am eagerly waiting for this fix as I tired the 'dev-master' version in composer update but still have my form not progressing past step 2 in my forms

**Comment by tractorcow** [comment]
Well, the fixes have been merged... what would still cause the issue that @kiwimediapro has noticed, @spekulatius ?

**Comment by kiwimediapro** [comment]
Do you need me to post any code etc?

**Comment by spekulatius** [comment]
Hello @kiwimediapro 

It worked for me after this fix. Some code would be great to see how your multiform is constructed.

Spek

**Comment by kiwimediapro** [comment]
Ok here goes.

in my composer.json i have   "silverstripe/multiform": "dev-master"

in my initial class PreplanningFrom.php

class PreplanningForm extends MultiForm {

    public static $start_step = 'RegistrationStep1';

    public function finish($data, $form) {
        parent::finish($data, $form);
        $steps = DataObject::get(
                        'MultiFormStep', "SessionID = {$this->session->ID}"
        );

        if ($steps) {
            foreach ($steps as $step) {
                
            }
        }

        $this->controller->redirect($controller->Link() . 'finished');
    }

}

then in RegistrationStep1.php

class RegistrationStep1 extends MultiFormStep {

    public static $next_steps = 'RegistrationStep2';

    public function getFields() {
        return FieldList::create(array(
                    TextField::create('BirthName', 'Your name at birth'),
                    DateField::create('DateOfBirth', 'Date of birth'),
                    TextField::create('BirthPlace', 'Place of birth'),
                    TextField::create('ArrivalYear', 'If not born in NZ, year of arrival here'),
                    TextField::create('YourOccupation', 'Your occupation'),
                    LiteralField::create('l3', '<hr>'),
                    TextField::create('MotherName', "Mother's full name"),
                    TextField::create('MotherMaidenName', "Mother's maiden name"),
                    TextField::create('MotherOccupation', "Mother's occupation"),
                    TextField::create('FatherName', "Father's full name"),
                    TextField::create('FatherOccupation', "Father's occupation"),
                        )
        );
    }

}

then in RegistrationStep2.php

class RegistrationStep2 extends MultiFormStep {

    public static $next_steps = 'ServiceRecordStep';

    public function getFields() {
        return FieldList::create(array(
                    DropdownField::create('MaritalStatus', 'My marital status', array('Married' => 'Married', 'Divorced' => 'Divorced')),
                    LiteralField::create("l3", "<hr>"),
                    LiteralField::create("l4", "<h4>Current marriage</h4>"),
                    TextField::create('MarriedTo', 'To'),
                    TextField::create('MarriedWhere', 'Where'),
                    TextField::create('MarriedAge', 'Age at marriage'),
                    LiteralField::create("l5", "<hr>"),
                    LiteralField::create("l6", "<h4>First previous marriage</h4>"),
                    TextField::create('PrevMarriedTo', 'To'),
                    TextField::create('PrevMarriedWhere', 'Where'),
                    TextField::create('PrevMarriedAge', 'Age at marriage'),
                    LiteralField::create("l7", "<hr>"),
                    LiteralField::create("l8", "<h4>Children – list  first names and birth names</h4>"),
                    TextareaField::create('ChildrenFemale', 'Female'),
                    TextareaField::create('ChildrenMale', 'Male'),
                    LiteralField::create("l9", "<hr>"),
                    DateField::create('SpouseBirthDate', "Living spouse's birth date"),
                    CountryDropdownField::create('EthnicOrigin', 'Your ethnic origin'),
                    TextField::create('Ethnicity', 'Other ethnicity'),
                    OptionsetField::create('MarriageCelebrant', 'Are you a marriage celebrant?', array('Yes' => 'Yes', 'No' => 'No')),
                    OptionsetField::create('JusticeOfPeace', 'Are you a justice of the peace?', array('Yes' => 'Yes', 'No' => 'No')),
                    TextField::create('HonoursHeld', 'Honours held'),

        ));
    }

}

then ServiceRecordStep.php

class ServiceRecordStep extends MultiFormStep {

    public static $next_steps = 'StepEnd';

    public function getFields() {
        return FieldList::create(array(
                    TextField::create('RegimentNumber', 'Regimental number / Service number'),
                    TextField::create('Regiment', 'Regiment'),
                    TextField::create('WarDecorations', 'War decorations'),
                    TextField::create('Rank', 'Rank'),
                    TextField::create('War', 'War')
        ));
    }

}

then StepEnd.php

class StepEnd extends MultiForm {

    public static $is_final_step = true;

}

**Comment by kiwimediapro** [comment]
Was the above code enough @spekulatius

**Comment by spekulatius** [comment]
Hello @kiwimediapro 

I haven't had time to look into this. I'll try to do it tomorrow.

Spek

**Comment by kiwimediapro** [comment]
HI there

I was wondering if you had time to look into my code yet to see why this fix is not working on my side.

Much appreciated.

**Comment by spekulatius** [comment]
Hello @kiwimediapro 

Unfortunately I haven't had a chance. Can you upload a zip with the files and your composer.lock to make analyzing easier?

Cheers,
Spek

**Comment by kiwimediapro** [comment]
@spekulatius I tried  a zip but it says
Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

**Comment by spekulatius** [comment]
ZIP is allow but it still complains? Im slightly confused by the message - you can upload it anywhere. I'm not worried, its totally up to you. You own server gives you the chance to make sure its deleted afterward ;)

**Comment by kiwimediapro** [comment]
Try this plz http://www.filedropper.com/ssmultiformissue

**Comment by spekulatius** [comment]
Got it, feel free to delete the file. I need to do some work. I'll check this later on.

**Comment by kiwimediapro** [comment]
Thank you very much

**Comment by spekulatius** [comment]
Hello @kiwimediapro 

I had a quick look over your files and noticed that your StepEnd class extends MultiForm, not MultiFormStep. I haven't verified this, but I would assume this causes at least some headache. Let me know if this caused the issue.

Btw: I would recommend you to use prefer-stable in your composer.json - this way you avoid unstable versions.

Spek

**Comment by kiwimediapro** [comment]
@spekulatius Thanks for that as I actually went of that code and saw that after I sent it to you. I made the correction but still do not seem to be able to get past step 2 or even go back to step 1.

Does that code run at all on your server?

Cheers

**Comment by spekulatius** [comment]
I haven't tried to run it @kiwimediapro - I just saw the issue and thought that probably won't work. Can you post your Form class which extends MultiForm?

**Comment by kiwimediapro** [comment]
@spekulatius 

I ran composer update with your suggestion for stable release and it now works.

Thanks very much

**Comment by spekulatius** [comment]
ah cool @kiwimediapro   :) That leave me to the thought "Will it break with the next release?" But at least we can close this for now @tractorcow
