### ISSUE TITLE
MultiFormProgressList

### ISSUE THREAD

**Issue by kiwimediapro** [silverstripe/silverstripe-multiform#57]
This does not work. A code error?

**$Top.URLSegment**

    <a href="{$Top.URLSegment}/?${Top.GetVar}={$SessionID}&amp;StepID={$ID}">

**Comment by spekulatius** [comment]
What exactly doesn't work @kiwimediapro ?

**Comment by kiwimediapro** [comment]
@spekulatius Thanks for replying
When I attempt to go back to a step such as http://localhost/mans.co.nz/pre-planning-form/?MultiFormSessionID=576&StepID=1639 the form step it goes back to is empty.

**Comment by spekulatius** [comment]
It doesn't matter which step you are going to? No data is prepopulated @kiwimediapro ?

**Comment by kiwimediapro** [comment]
No. None of the steps prepopulate.

Here is more info
This my latest step
http://localhost/twentymans.co.nz/pre-planning-form/?MultiFormSessionID=582&StepID=1773

Yet in the DB 
MultiformSession
ID	ClassName	LastEdited	Created	Hash	IsComplete	SubmitterID	CurrentStepID
584	MultiFormSession	05-Jan-16 2:28:42 PM	05-Jan-16 2:28:39 PM	dca4db02159cb0b2e1934a3562f896f84f70e842	0	22	1771

And in the MultiformStep table no update
ID	ClassName	LastEdited	Created	Data	SessionID
1000	RegistrationStep1	17-Dec-15 3:39:00 PM	17-Dec-15 3:39:00 PM	(null)	479

**Comment by kiwimediapro** [comment]
Should i run composer and update your module. It is set to 'dev-master'

**Comment by spekulatius** [comment]
Its not 'my' module. I'm just helping out here and there ;)

Give it a short and see if that fixes the problem.

**Comment by kiwimediapro** [comment]
Oh right. Sorry module owner.

Ok will try that.

**Comment by kiwimediapro** [comment]
ok i see now what is wrong 

the steps link should be 
pre-planning-form/?MultiFormSessionID=012558d074094abba8868b570bb8c996b7914532&StepID=2

and not

pre-planning-form/?MultiFormSessionID=1&StepID=2

**Comment by spekulatius** [comment]
okay, are you sure about this @kiwimediapro ?

**Comment by kiwimediapro** [comment]
Testing and will let you know as somehow the $SessionID in the step link

{$Top.URLSegment}/?${Top.GetVar}={__$SessionID__}&amp;StepID={$ID}

gives me

pre-planning-form/?MultiFormSessionID=1&StepID=2

Which does not repopulate the forms and messes up all the data.

Executing this as the link works.

pre-planning-form/?MultiFormSessionID=012558d074094abba8868b570bb8c996b7914532&StepID=2

Now I need to find out the correct var for the Session ID as the one below appears incorrect

{$Top.URLSegment}/?${Top.GetVar}={__$SessionID__}&amp;StepID={$ID}

Can you confirm whether the Progress list link should look like this:

MultiFormSessionID=__1__&StepID=__1__

or this

MultiFormSessionID=__012558d074094abba8868b570bb8c996b7914532__&StepID=__1__

**Comment by spekulatius** [comment]
My Links look like this: MultiFormSessionID=012558d074094abba8868b570bb8c996b7914532&StepID=1

**Comment by kiwimediapro** [comment]
Right

That is what I realized is wrong with the code I have. I will need to do a code compare and find the diff.

Thanks for that confirmation. Will post here my findings if relevant

**Comment by spekulatius** [comment]
no problem
