### ISSUE TITLE
MultiForm doesn't work for fields with array notation

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-multiform#6]
From http://open.silverstripe.org/ticket/4243

If you specify a step with a fieldset like this, with some fields in array notation (square brackets):

    function getFields() {
	$fields = new FieldSet();
	$nameCount = 5;
	for($i = 0; $i < $nameCount; $i++) {
		$fields->push(new TextField("Name[$i]", "Name $i"));
	}
	return $fields
   }

You'd expect that this would save an array called "Name" with the keys of $i with each value inside it. However, it just saves them as literally "Name[0]", "Name[1]" at the moment.

This is because $form->getData() on the next() and prev() methods on MultiForm? simply just get each data field's value without checking the square brackets for any special meaning.

**Comment by wilr** [comment]
Tested with FirstName[1], FirstName[2] and data successfully is passed through to finish() and when reloading the step it works.
