### ISSUE TITLE
Skip validation on "Back"

### ISSUE THREAD

**Issue by bjarman** [silverstripe/silverstripe-multiform#60]
Using getValidator() on a step to make a field required makes it impossible to navigate to previous step. Is there a good way to allow user to navigate to previous step using back button without validating the current step?

**Comment by kiwimediapro** [comment]
I have the same issue particularly with option/radio fields.

**Comment by bjarman** [comment]
I installed zenvalidator and navigating to previous step seems to work. Still don't know why this does not work using ss built in validator though...

**Comment by kiwimediapro** [comment]
I already have Zend Validator installed. Do I need to do anything else?

**Comment by wilr** [comment]
I have used the latest multiform and tested this and it works fine. Back button has a formnovalidate method attached.
