### ISSUE TITLE
Update sample code in documentation

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-multiform#71]
In section 5 of the README.md update the following:
`'Content' => '<p>You have successfully submitted the form!</p>'` 
to 
`'Content' => DBHTMLText::create('<p>You have successfully submitted the form!</p>')`
to avoid the HTML tags being escaped and rendered verbatim.

**Comment by robbieaverill** [comment]
Would you like to make a PR to update it?

**Comment by raissanorth** [comment]
@robbieaverill Done with https://github.com/silverstripe/silverstripe-multiform/pull/72
