### ISSUE TITLE
SS4.2.1 Form Action using Namespace causes 404

### ISSUE THREAD

**Issue by aledbrown** [silverstripe/silverstripe-multiform#77]
Hi

Thanks for upgrading MultiForm to SS4. I'm upgrading an SS3 MultiForm to SS4 and I've run into one minor difficulty.

The site is working dev/build?flush=1 no errors.

The form is rendering the first page and if I fill it in and press next the URL adds /My/Namesapce/FormClass to the URL.

If I modify that action URL in the Code Inspector and take out the /My/Namespace bit and re-submit the form in the browser it uses custom validators and goes to the next step correctly and renders the next form.

How do I stop MultiForm from using the additional bits of the namespace in the Form Action?

Thanks
Aled

**Comment by robbieaverill** [comment]
Thanks for reporting this issue. Often in SilverStripe 4 when class names are used in URLs we sanitise and unsanitise them by replacing backslashes with dashes. You can see examples in ModelAdmin of the methods that do this. Perhaps you’d like to make a pull request to add them to this module too?

**Comment by aledbrown** [comment]
I've not had any luck fixing this issue yet. I've been through all the code in Multiform and I've also been through all the code in UserDefinedForms in case there was something similar there.

I've worked out that if the formAction was Class.shortName that the next step would work by modifying it in the browser inspector. It would not work if the My\Namespace\Class was converted to My_Namespace_Class though. It needs to be the short Classname then the next step form action works.

Adding the full namespace action to allowed_actions didn't work.

I haven't been able to work out which method in multiform needs to be modified. My best guesses are public function FormAction() or public function getDisplayLink() in MultiForm.php.

I'm sorry I've not been able to submit a PR for this issue yet.

**Comment by icecaster** [comment]
Defining a FormObjectLink() in your controller fixes this issue:

    public function FormObjectLink()
    {
        return $this->Link("Form");
    }
