### ISSUE TITLE
One query in MultiForm.php does not double quote fields, which breaks this module on all Postgres systems

### ISSUE THREAD

**Issue by muppsy007** [silverstripe/silverstripe-multiform#87]
Branch 1.3.

[Here is the offending line](https://github.com/silverstripe/silverstripe-multiform/blob/6a019d25944680025683d0ff9427c6e80a1fe8b8/code/model/MultiForm.php#L211).

```
$currentStep = DataObject::get_one(
    'MultiFormStep',
    array(
        'SessionID' => $this->session->ID,
        'ID' => $StepID
    )
 );
```

Note SessionID and ID are not double quoted. This results in a casing error from Postgres

> pg_query_params(): Query failed: ERROR: column "sessionid" does not exist LINE 5: WHERE (SessionID = $1)

If I change the params in that get_one call to include double quotes, we're good.

```
array(
     '"SessionID"' => $this->session->ID,
     '"ID"' => $StepID
)
```

Interestingly, there are seven other instances of get_one() and four instances of get() in this module. This is the only one that is not double quoted. The rest all use escaped double quote notation. [For example](https://github.com/silverstripe/silverstripe-multiform/blob/6a019d25944680025683d0ff9427c6e80a1fe8b8/code/model/MultiForm.php#L521):

```
// Get the previous step of the class instance returned from $currentStep->getPreviousStep()
$prevStep = DataObject::get_one($prevStepClass, "\"SessionID\" = {$this->session->ID}");
```

If I do a PR for this, will it be merged?

**Comment by dhensby** [comment]
> If I do a PR for this, will it be merged?

PRs always welcome

**Comment by wilr** [comment]
Closing as this is now using a filter field in supported versions
