### ISSUE TITLE
Error 500 while loading page on SilverStripe 5

### ISSUE THREAD

**Issue by digitweaks** [silverstripe/silverstripe-multiform#88]
I installed and used successfully the module on different SS4.13 websites, had no issue whatsoever. Then rebuilt the same sites under SS5 and everything works but Multiform. I don't know what happens but all I have is white page with an error 500. No error logged, nothing.

So I don't know, was that tested on SS5 or is it just possible to install it but without it being tested?

I had to revert 4 websites back to SS4.13 due to this module and there's nothing pointing to any mistake on my side.

Any clue or fix is welcome, thanks

**Comment by NightJar** [comment]
~Please post a stacktrace to help with the debugging :)~
I presume this error is happening in a development environment.
Please ensure logging is configured, e.g. with `SS_ERROR_LOG`

https://docs.silverstripe.org/en/5/developer_guides/debugging/error_handling/#logging-to-a-file

This should point to some reason for the 500 error, which would greatly help with debugging if shared :)

*edit
Be sure to edit sensitive details if there is a concern.

**Comment by Firesphere** [comment]
> Please post a stacktrace to help with the debugging :)

> No error logged, nothing.

...

**Comment by NightJar** [comment]
Fair point.
Stacktrace is the wrong focus.
There must be a log _somewhere_ that gives a clue though ;)

**Comment by digitweaks** [comment]
No logs at all, that's why I can't even debug it or create a PR. I have the SS_ERROG_LOG activated at all time on these development enviroments but it's totally empty

**Comment by Firesphere** [comment]
An error 500 with no logs, most commonly means an Apache error so far up the stack, that PHP is even barely hit, or the PHP stack can't fully execute, including the loading of the error logger...

If you can, try running xdebug, and step through slowly, inspecting each step.
It's going to be tedious to do, but probably impossible to get anything useful without trying even.

**Comment by digitweaks** [comment]
Not familiar with xdebug but will check how that works

**Comment by digitweaks** [comment]
I looked into xdebug but I won't be able to install it on my old local machine limited to PHP7.4 due to MacOS being locked at OS10.11.6 and on the remote server I have an OVH performance but we can't install xdebug on it, for that I would need a VM or dedicated server. 

The code I have should work though, it seemed to work on SS4.13 and SS5 before then I've updated all the sites to the latest SS5 and multiform is the only impacted module. As I have no idea on how to solve this with my old machine and am limited to the OVH server, I will just downgrade to SS4.13

**Comment by NightJar** [comment]
After some discussion over Slack @digitweaks has clarified that the issue occurs when loading any page that has a mutli-form on it.
The initial load is enough to trigger the 500 error, so should be reasonably easy to replicate.

**Comment by digitweaks** [comment]
From the test with Phpunit:
vendor/bin/phpunit vendor/silverstripe/multiform/tests/MultiFormTest.php
vendor/bin/phpunit vendor/silverstripe/multiform/tests/MultiFormObjectDecoratorTest.php

The issue seems to be related to the creation of some database fields. I have administration rights for CREATE and all other SQL functions activated.

Access denied for user 'CorrectDBusername'@'%' to database 'ss_tmpdb******'.... in /home/cunahkn/girls/vendor/silverstripe/framework/src/ORM/Connect/DBConnector.php:63

**Comment by digitweaks** [comment]
To be clear I didn't change anything between SS4.13 and SS5 in terms of database permissions or credentials and had no issue with DB connection outside of these tests. In the same time the test with 4.13 also fails but the form appears and works properly so I'm not even sure I'm running the tests correctly.

**Comment by digitweaks** [comment]
Is there something special to set for the tests to reflect the actual situation?

**Comment by digitweaks** [comment]
So I'm closing the ticket as the issue comes from the incompatibility of the dependency symfony/var-exporter v7.0.7 with Php8.1. After trying to install SS5 directly on the production server via SSH and composer, the module cannot be installed under Php8.1. Minimim requirement is Php8.2

**Comment by digitweaks** [comment]
After updating to Php8.2 and reinstalling everything from scratch via composer directly on the production server, still the same issue, so the update to Php8.2 didn't solve the problem.

**Comment by digitweaks** [comment]
Ok, finally I got the module to work with some modifications, if anyone else has the same issue:
- The module works with Silverstripe 5 with Php8.2 so if on Php8.1, an upgrade is necessary unless you tweak the composer.json
- The name of the page controller must be YourPageController and not YourPage_Controller, for some reason that made the form not appearing even though it works perfectly fine on SS4.13
- I had a memory overflow related to a Link() function that didn't cause any issue on SS4.13 but not necessary on SS5

**Comment by GuySartorelli** [comment]
> The module works with Silverstripe 5 with Php8.2 so if on Php8.1, an upgrade is necessary unless you tweak the composer.json

What tweak needs to be made?

> I had a memory overflow related to a Link() function that didn't cause any issue on SS4.13 but not necessary on SS5

What that a method that was implemented in your project? Or was it in core or in a module somewhere? If it's in core or in a module it sounds like that will need to be fixed still.

**Comment by digitweaks** [comment]
@GuySartorelli For the module itself if you want to make it 100% compatible with Php8.1 then the dependency of Symfony/var-exporter needs to be also compatible with Php8.1 which I guess can be done with a previous version. The rest is just tweaks I did but that are not core or in a module.

**Comment by GuySartorelli** [comment]
This module doesn't have an dependency on `symfony/var-exporter`.... what do you mean?

**Comment by digitweaks** [comment]
When we install via composer there's a message stating that symfony/var-exporter doesn't meet the Php8.1 requirements, if I force the installation with --ignore-platform-req PHP then it can be installed. 

That said... I didn't try under Php8.1 with the latest changes I did, so maybe it works with Php8.1 if we force the installation.

**Comment by digitweaks** [comment]
Let me check, I can switch back to Php8.1 for a moment

**Comment by digitweaks** [comment]
Obviously now the SS5 requires Php8.2 so I can't test, but as you mentioned the module doesn't depend on symfony/var-exporter so I will assume my code had to be adapted to SS5 and the module therefore is fine.

**Comment by GuySartorelli** [comment]
The version of `symfony/var-exporter` that installs for me is `6.4.7`, which [supports PHP 8.1](https://github.com/symfony/var-exporter/blob/v6.4.7/composer.json). This is with a fresh installation of `silverstripe/installer` 5.2 with this module installed.

You might want to run `composer why symfony/var-exporter` to see why you're getting a version that is incompatible with PHP 8.1 - it's definitely not anything to do with this module.

**Comment by GuySartorelli** [comment]
> Obviously now the SS5 requires Php8.2

No, it very much does not.

**Comment by digitweaks** [comment]
It's not related to that module:
 symfony/cache v6.4.7 requires symfony/var-exporter (^6.3.6|^7.0)

**Comment by GuySartorelli** [comment]
That constraint allows for you a PHP 8.1 compatible version of `symfony/var-exporter`, so it seems like you might have something like [a specific php version defined in your composer.json file](https://getcomposer.org/doc/06-config.md#platform) like below:

```json
{
    "config": {
        "platform": {
            "php": 8.2
        }
    }
}
```

Anyway, my curiosity has been satisfied, sounds like there's no issues for this module or any supported modules. Thank you for bearing with me.

**Comment by digitweaks** [comment]
I reverted back to PHP 8.1 then did composer update and I can confirm the module works fine with PHP8.1

**Comment by digitweaks** [comment]
So the module has no issues, I had to adapt my code. At least if someone stumbles upon that same issue with PHP 8.1, there's enough resolution notes. Thanks a lot, my curiosity is also satisfied.
